### ISSUE TITLE
This module is black-box and can be used only for education purposes.

### ISSUE THREAD

**Issue by langpavel** [Emilios1995/redux-create-module#3]
I cannot imagine usefulness in real world scenario.
It looks like good convention. Not at all against. But it should be really splitted in separate files responsible for doing that things.
You are squashing **redux *pattern*** to one function which returns *the module*, but you should keep in mind, that action creators can create multiple actions like `*_START`, `*_SUCCESS` or `*_ERROR`... or sagas, (personally I dislike them ;-) )

But, I should not only hate. **You catched up all important things of module.** It should expose *action creators* and *default reducer* and *action names*.

But I really dislike the way of black-boxing and indirection.

**Comment by Emilios1995** [comment]
I do see a lot of educational value in this module, that's why I wrote a blog post about it.
But I also use it in my real-world applications. 
I don't understand how splitting this into separate files will improve the module's usefulness. You are free to make a PR to make yourself clearer, and if I don't like it, you can always fork this and make it your own!

**Comment by langpavel** [comment]
Hi, thanks! Don't take me bad. I don't need fork and I don't need some central point packing of my actions and reducers into module. That's my point :-)
